### ISSUE TITLE
EMQX MQTT auto discover not working.

### ISSUE THREAD

**Issue by RamonBell** [home-assistant/.github#12]
I was trying to integrate EMQX as my MQTT broker. I was running it as an LXC container in proxmox alongside home assistant core which is also an LXC container. Both were configured successfully as I was able to publish topics to different items in node Red using the broker. I tested in three different installation types of home assistant and if you are running EMQX separately from home assistant, not the integration. The auto discovery of MQTT will not work. I tried changing the discovery topic and it still will not find it. The second I went back to mosquito it was auto discovered and working just fine.

**Comment by frenck** [comment]
This is not EMQX...

Seems like you are in the wrong repo.

../Frenck
