### ISSUE TITLE
Devices "disabled by config entry"

### ISSUE THREAD

**Issue by testpionier** [home-assistant/.github#9]
I've got some WIZ lights of the newest generation and some lights of the generation before. With the newer ones everthing works. The older ones are also recognized by Home Assistant, but are "disabled by config entry". That means, in the end I can't used them.

Any idea how this problem can be solved?

**Comment by frenck** [comment]
Thank you for reaching out.  We use GitHub for tracking issues, not for providing support.

If you are in need of support, you should try our [Community Forum](https://community.home-assistant.io) or join our [Discord chat server](https://discord.gg/c5DvZ4e).

You are more likely to get the answer you are looking for in those places.

Thanks! 👍

**Comment by testpionier** [comment]
It looks as if it is as bug of a home assistant plug in, but I missed to label it correctly yet.
